/*
 * notify_dispatch_prof.cpp — PyTorch pybind wrapper for NotifyDispatchProf operator
 *
 * Calls the CANN custom operator via EXEC_NPU_CMD macro.
 * The aclnnNotifyDispatchProf / aclnnNotifyDispatchProfGetWorkspaceSize functions
 * are auto-generated by CANN opbuild from the op_host registration.
 */

#include "pytorch_extension/pytorch_npu_helper.hpp"

std::vector<at::Tensor> NotifyDispatchProfImpl(
    const at::Tensor &sendData,
    const at::Tensor &tokenPerExpertData,
    const at::Tensor &profBuf,
    int64_t sendCount,
    int64_t numTokens,
    const std::string &commGroup,
    int64_t rankSize,
    int64_t rankId,
    int64_t localRankSize,
    int64_t localRankId)
{
    // numExperts = sendCount / sendPerGroup, sendPerGroup = 3
    int64_t numExperts = sendCount / 3;

    // Allocate output tensors
    auto options = sendData.options();
    auto sendDataOffset = at::empty({numExperts}, options);
    auto recvData = at::empty({sendCount}, options);
    auto totalRecvTokens = at::empty({1}, options.dtype(at::kInt));
    auto recvCount = at::empty({numExperts}, options.dtype(at::kInt));
    auto recvOffset = at::empty({numExperts}, options.dtype(at::kInt));
    auto maxBs = at::empty({1}, options.dtype(at::kInt));
    auto recvTokensPerExpert = at::empty({numExperts / rankSize}, options.dtype(at::kLong));

    const char *commGroupPtr = commGroup.c_str();
    EXEC_NPU_CMD(aclnnNotifyDispatchProf, sendData, tokenPerExpertData, profBuf,
                 sendCount, numTokens, commGroupPtr,
                 rankSize, rankId, localRankSize, localRankId,
                 sendDataOffset, recvData, totalRecvTokens,
                 recvCount, recvOffset, maxBs, recvTokensPerExpert);
          

    return {sendDataOffset, recvData, totalRecvTokens, recvCount, recvOffset, maxBs, recvTokensPerExpert};
}
