/*
 * vec_add_prof.cpp — PyTorch pybind wrapper for VecAddProf operator
 *
 * Calls the CANN custom operator via EXEC_NPU_CMD macro.
 * The aclnnVecAddProf / aclnnVecAddProfGetWorkspaceSize functions
 * are auto-generated by CANN opbuild from the op_host registration.
 */

#include "pytorch_extension/pytorch_npu_helper.hpp"

at::Tensor VecAddProfImplAutograd(
    const at::Tensor &x,
    const at::Tensor &y,
    const at::Tensor &prof_buf)
{
    auto z = at::empty_like(x);
    EXEC_NPU_CMD(aclnnVecAddProf, x, y, prof_buf, z);
    return z;
}
